### ISSUE TITLE
Error deploying UI

### ISSUE THREAD

**Issue by rmthurman** [jennifermarsman/cognitive-search-qna-solution#19]
Getting an error deploying the UI application:

Command: deploy.cmd
Handling node.js deployment.
Looking for app.js/server.js under site root.
Invalid start-up command "react-scripts start" in package.json. Please use the format "node <script relative path>".
Node.js versions available on the platform are: 0.6.20, 0.8.2, 0.8.19, 0.8.26, 0.8.27, 0.8.28, 0.10.5, 0.10.18, 0.10.21, 0.10.24, 0.10.26, 0.10.28, 0.10.29, 0.10.31, 0.10.32, 0.10.40, 0.12.0, 0.12.2, 0.12.3, 0.12.6, 4.0.0, 4.1.0, 4.1.2, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.3.0, 4.3.2, 4.4.0, 4.4.1, 4.4.6, 4.4.7, 4.5.0, 4.6.0, 4.6.1, 4.8.4, 5.0.0, 5.1.1, 5.3.0, 5.4.0, 5.5.0, 5.6.0, 5.7.0, 5.7.1, 5.8.0, 5.9.1, 6.0.0, 6.1.0, 6.2.2, 6.3.0, 6.5.0, 6.6.0, 6.7.0, 6.9.0, 6.9.1, 6.9.2, 6.9.4, 6.9.5, 6.10.0, 6.10.3, 6.11.1, 6.11.2, 6.11.5, 6.12.2, 6.12.3, 7.0.0, 7.1.0, 7.2.0, 7.3.0, 7.4.0, 7.5.0, 7.6.0, 7.7.0, 7.7.4, 7.10.0, 7.10.1, 8.0.0, 8.1.4, 8.4.0, 8.5.0, 8.7.0, 8.8.0, 8.8.1, 8.9.0, 8.9.3, 8.9.4, 8.10.0, 8.11.1, 8.17.0, 10.0.0, 10.6.0, 10.14.1, 10.15.2, 10.16.3, 10.19.0, 12.13.0, 12.15.0, 12.18.0, 14.10.1, 14.15.0.
Missing server.js/app.js files, web.config is not generated
Selected node.js version 14.15.0. Use package.json file to choose a different version.
Selected npm version 6.14.8
Updating iisnode.yml at D:\home\site\wwwroot\iisnode.yml
SETTING VARIABLES
INSTALLING AND BUILDING APP
Failed exitCode=-1073741819, command="D:\Program Files (x86)\nodejs\14.15.0\node.exe" "D:\Program Files (x86)\npm\6.14.8\node_modules\npm\bin\npm-cli.js" cache clean --force
RUNNING NPM INSTALL
Thread was being aborted.
Thread was being aborted.

**Comment by dereklegenzoff** [comment]
Hi Randy - thanks for flagging this and for including the detailed error logs. The deployment sometimes hits transient failures during `npm install` step, currently. If you try deploying again, you should hopefully be able to get it to work.

We're working to move to a zip deploy technique to improve the reliability of this.

**Comment by dereklegenzoff** [comment]
The deployment method has been updated. It should now be faster and reliable. I'll close this issue for now but please feel free to re-open it if you face any additional issues.
